import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Container, Box } from '@mui/material'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          
          <Container maxWidth="lg">
            <Box sx={{ bgcolor: '#cfe8fc', height: '100vh' }}>
              {children}
            </Box>
          </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
